//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/mahmoud/Home/projects/Graduation/Testing/Geem/Parser/Geem.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Geem.Parser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GeemParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, LP=13, RP=14, LSB=15, RSB=16, LCB=17, RCB=18, 
		ADDRESS_OF_OPERATOR=19, VALUE_INSIDE_OPERATOR=20, SIZE_OF=21, FASLA=22, 
		FASLA_MANQUOTA=23, COLON=24, PLUS=25, MINUS=26, MULTIPLY=27, DIVIDE=28, 
		ARABIC_MODULS=29, MODULUS=30, LAND=31, LOR=32, LNOT=33, SL_SYM=34, SRA_SYM=35, 
		SR_SYM=36, BAND_SYM=37, BOR_SYM=38, BXOR_SYM=39, BNOT_SYM=40, LTE_SYM=41, 
		GTE_SYM=42, LT_SYM=43, GT_SYM=44, EQUAL_SYM=45, NOTEQ_SYM=46, ASSIGN_SYM=47, 
		FUNC_KEYWORD=48, OP_KEYWORD=49, RET_KEYWORD=50, RES_KEYWORD=51, IF_KEYWORD=52, 
		WHILE_KEYWORD=53, BREAK_KEYWORD=54, CONTINUE_KEYWORRD=55, INT_DATA_TYPE=56, 
		UINT_DATA_TYPE=57, BYTE_DATA_TYPE=58, UBYTE_DATA_TYPE=59, SHORT_DATA_TYPE=60, 
		USHORT_DATA_TYPE=61, LONG_DATA_TYPE=62, ULONG_DATA_TYPE=63, BOOL_DATA_TYPE=64, 
		WHITE_SPACE=65, ID=66;
	public const int
		RULE_program = 0, RULE_globalVarDecl = 1, RULE_inititalization = 2, RULE_functionDecl = 3, 
		RULE_operationDecl = 4, RULE_parameter = 5, RULE_paramList = 6, RULE_argument = 7, 
		RULE_argumentList = 8, RULE_expression = 9, RULE_int_literal = 10, RULE_comparison_op = 11, 
		RULE_equality_op = 12, RULE_statement = 13, RULE_statementList = 14, RULE_operationStat = 15, 
		RULE_assignmentStat = 16, RULE_ifStat = 17, RULE_whileStat = 18, RULE_returnStat = 19, 
		RULE_resultStat = 20, RULE_varDecl = 21, RULE_commandStat = 22, RULE_dataType = 23, 
		RULE_command = 24;
	public static readonly string[] ruleNames = {
		"program", "globalVarDecl", "inititalization", "functionDecl", "operationDecl", 
		"parameter", "paramList", "argument", "argumentList", "expression", "int_literal", 
		"comparison_op", "equality_op", "statement", "statementList", "operationStat", 
		"assignmentStat", "ifStat", "whileStat", "returnStat", "resultStat", "varDecl", 
		"commandStat", "dataType", "command"
	};

	private static readonly string[] _LiteralNames = {
		null, "'\u0660'", "'\u0661'", "'\u0662'", "'\u0663'", "'\u0664'", "'\u0665'", 
		"'\u0666'", "'\u0667'", "'\u0668'", "'\u0669'", "'\u0625\u0637\u0628\u0639'", 
		"'\u0627\u0637\u0628\u0639'", "'('", "')'", "'['", "']'", "'{'", "'}'", 
		"'&:'", "'*:'", "'\u062D\u062C\u0645:'", "'\u060C'", "'\u061B'", "':'", 
		"'+'", "'-'", "'\u00D7'", "'\u00F7'", "'\u066A'", "'%'", "'&&'", "'||'", 
		"'!'", "'<<'", "'>>>'", "'>>'", "'&'", "'|'", "'^'", "'~'", "'<='", "'>='", 
		"'<'", "'>'", "'=='", "'!='", "':='", "'\u062F\u0627\u0644\u0629'", "'\u0639\u0645\u0644\u064A\u0629'", 
		"'\u0631\u062C\u0648\u0639'", "'\u0627\u0644\u0646\u0627\u062A\u062C'", 
		null, "'\u0637\u0627\u0644\u0645\u0627'", "'\u0642\u0637\u0639'", null, 
		"'\u0635\u062D\u064A\u062D_\u0664'", "'\u0637\u0628\u064A\u0639\u064A_\u0664'", 
		"'\u0635\u062D\u064A\u062D_\u0661'", "'\u0637\u0628\u064A\u0639\u064A_\u0661'", 
		"'\u0635\u062D\u064A\u062D_\u0662'", "'\u0637\u0628\u064A\u0639\u064A_\u0662'", 
		"'\u0635\u062D\u064A\u062D_\u0668'", "'\u0637\u0628\u064A\u0639\u064A_\u0668'", 
		"'\u0645\u0646\u0637\u0642\u064A'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "LP", "RP", "LSB", "RSB", "LCB", "RCB", "ADDRESS_OF_OPERATOR", "VALUE_INSIDE_OPERATOR", 
		"SIZE_OF", "FASLA", "FASLA_MANQUOTA", "COLON", "PLUS", "MINUS", "MULTIPLY", 
		"DIVIDE", "ARABIC_MODULS", "MODULUS", "LAND", "LOR", "LNOT", "SL_SYM", 
		"SRA_SYM", "SR_SYM", "BAND_SYM", "BOR_SYM", "BXOR_SYM", "BNOT_SYM", "LTE_SYM", 
		"GTE_SYM", "LT_SYM", "GT_SYM", "EQUAL_SYM", "NOTEQ_SYM", "ASSIGN_SYM", 
		"FUNC_KEYWORD", "OP_KEYWORD", "RET_KEYWORD", "RES_KEYWORD", "IF_KEYWORD", 
		"WHILE_KEYWORD", "BREAK_KEYWORD", "CONTINUE_KEYWORRD", "INT_DATA_TYPE", 
		"UINT_DATA_TYPE", "BYTE_DATA_TYPE", "UBYTE_DATA_TYPE", "SHORT_DATA_TYPE", 
		"USHORT_DATA_TYPE", "LONG_DATA_TYPE", "ULONG_DATA_TYPE", "BOOL_DATA_TYPE", 
		"WHITE_SPACE", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Geem.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GeemParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public GeemParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public GeemParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		public GlobalVarDeclContext[] globalVarDecl() {
			return GetRuleContexts<GlobalVarDeclContext>();
		}
		public GlobalVarDeclContext globalVarDecl(int i) {
			return GetRuleContext<GlobalVarDeclContext>(i);
		}
		public FunctionDeclContext[] functionDecl() {
			return GetRuleContexts<FunctionDeclContext>();
		}
		public FunctionDeclContext functionDecl(int i) {
			return GetRuleContext<FunctionDeclContext>(i);
		}
		public OperationDeclContext[] operationDecl() {
			return GetRuleContexts<OperationDeclContext>();
		}
		public OperationDeclContext operationDecl(int i) {
			return GetRuleContext<OperationDeclContext>(i);
		}
		public CommandStatContext[] commandStat() {
			return GetRuleContexts<CommandStatContext>();
		}
		public CommandStatContext commandStat(int i) {
			return GetRuleContext<CommandStatContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 54;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case INT_DATA_TYPE:
				case UINT_DATA_TYPE:
				case BYTE_DATA_TYPE:
				case UBYTE_DATA_TYPE:
				case SHORT_DATA_TYPE:
				case USHORT_DATA_TYPE:
				case LONG_DATA_TYPE:
				case ULONG_DATA_TYPE:
					{
					State = 50; globalVarDecl();
					}
					break;
				case FUNC_KEYWORD:
					{
					State = 51; functionDecl();
					}
					break;
				case OP_KEYWORD:
					{
					State = 52; operationDecl();
					}
					break;
				case COLON:
					{
					State = 53; commandStat();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 56;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << COLON) | (1L << FUNC_KEYWORD) | (1L << OP_KEYWORD) | (1L << INT_DATA_TYPE) | (1L << UINT_DATA_TYPE) | (1L << BYTE_DATA_TYPE) | (1L << UBYTE_DATA_TYPE) | (1L << SHORT_DATA_TYPE) | (1L << USHORT_DATA_TYPE) | (1L << LONG_DATA_TYPE) | (1L << ULONG_DATA_TYPE))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GlobalVarDeclContext : ParserRuleContext {
		public DataTypeContext dataType() {
			return GetRuleContext<DataTypeContext>(0);
		}
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public InititalizationContext inititalization() {
			return GetRuleContext<InititalizationContext>(0);
		}
		public ITerminalNode FASLA_MANQUOTA() { return GetToken(GeemParser.FASLA_MANQUOTA, 0); }
		public GlobalVarDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_globalVarDecl; } }
	}

	[RuleVersion(0)]
	public GlobalVarDeclContext globalVarDecl() {
		GlobalVarDeclContext _localctx = new GlobalVarDeclContext(Context, State);
		EnterRule(_localctx, 2, RULE_globalVarDecl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58; dataType();
			State = 59; Match(ID);
			State = 60; inititalization();
			State = 61; Match(FASLA_MANQUOTA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InititalizationContext : ParserRuleContext {
		public ITerminalNode ASSIGN_SYM() { return GetToken(GeemParser.ASSIGN_SYM, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public InititalizationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_inititalization; } }
	}

	[RuleVersion(0)]
	public InititalizationContext inititalization() {
		InititalizationContext _localctx = new InititalizationContext(Context, State);
		EnterRule(_localctx, 4, RULE_inititalization);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 63; Match(ASSIGN_SYM);
			State = 64; expression(0);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDeclContext : ParserRuleContext {
		public ITerminalNode FUNC_KEYWORD() { return GetToken(GeemParser.FUNC_KEYWORD, 0); }
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public ITerminalNode RP() { return GetToken(GeemParser.RP, 0); }
		public ParamListContext paramList() {
			return GetRuleContext<ParamListContext>(0);
		}
		public ITerminalNode LP() { return GetToken(GeemParser.LP, 0); }
		public ITerminalNode COLON() { return GetToken(GeemParser.COLON, 0); }
		public DataTypeContext dataType() {
			return GetRuleContext<DataTypeContext>(0);
		}
		public ITerminalNode RCB() { return GetToken(GeemParser.RCB, 0); }
		public StatementListContext statementList() {
			return GetRuleContext<StatementListContext>(0);
		}
		public ITerminalNode LCB() { return GetToken(GeemParser.LCB, 0); }
		public FunctionDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDecl; } }
	}

	[RuleVersion(0)]
	public FunctionDeclContext functionDecl() {
		FunctionDeclContext _localctx = new FunctionDeclContext(Context, State);
		EnterRule(_localctx, 6, RULE_functionDecl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66; Match(FUNC_KEYWORD);
			State = 67; Match(ID);
			State = 68; Match(RP);
			State = 69; paramList();
			State = 70; Match(LP);
			State = 71; Match(COLON);
			State = 72; dataType();
			State = 73; Match(RCB);
			State = 74; statementList();
			State = 75; Match(LCB);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationDeclContext : ParserRuleContext {
		public ITerminalNode OP_KEYWORD() { return GetToken(GeemParser.OP_KEYWORD, 0); }
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public ITerminalNode RP() { return GetToken(GeemParser.RP, 0); }
		public ParamListContext paramList() {
			return GetRuleContext<ParamListContext>(0);
		}
		public ITerminalNode LP() { return GetToken(GeemParser.LP, 0); }
		public ITerminalNode RCB() { return GetToken(GeemParser.RCB, 0); }
		public StatementListContext statementList() {
			return GetRuleContext<StatementListContext>(0);
		}
		public ITerminalNode LCB() { return GetToken(GeemParser.LCB, 0); }
		public OperationDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operationDecl; } }
	}

	[RuleVersion(0)]
	public OperationDeclContext operationDecl() {
		OperationDeclContext _localctx = new OperationDeclContext(Context, State);
		EnterRule(_localctx, 8, RULE_operationDecl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77; Match(OP_KEYWORD);
			State = 78; Match(ID);
			State = 79; Match(RP);
			State = 80; paramList();
			State = 81; Match(LP);
			State = 82; Match(RCB);
			State = 83; statementList();
			State = 84; Match(LCB);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterContext : ParserRuleContext {
		public DataTypeContext dataType() {
			return GetRuleContext<DataTypeContext>(0);
		}
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public ParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter; } }
	}

	[RuleVersion(0)]
	public ParameterContext parameter() {
		ParameterContext _localctx = new ParameterContext(Context, State);
		EnterRule(_localctx, 10, RULE_parameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86; dataType();
			State = 87; Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamListContext : ParserRuleContext {
		public ParameterContext[] parameter() {
			return GetRuleContexts<ParameterContext>();
		}
		public ParameterContext parameter(int i) {
			return GetRuleContext<ParameterContext>(i);
		}
		public ITerminalNode[] FASLA() { return GetTokens(GeemParser.FASLA); }
		public ITerminalNode FASLA(int i) {
			return GetToken(GeemParser.FASLA, i);
		}
		public ParamListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_paramList; } }
	}

	[RuleVersion(0)]
	public ParamListContext paramList() {
		ParamListContext _localctx = new ParamListContext(Context, State);
		EnterRule(_localctx, 12, RULE_paramList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INT_DATA_TYPE) | (1L << UINT_DATA_TYPE) | (1L << BYTE_DATA_TYPE) | (1L << UBYTE_DATA_TYPE) | (1L << SHORT_DATA_TYPE) | (1L << USHORT_DATA_TYPE) | (1L << LONG_DATA_TYPE) | (1L << ULONG_DATA_TYPE))) != 0)) {
				{
				State = 89; parameter();
				State = 94;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==FASLA) {
					{
					{
					State = 90; Match(FASLA);
					State = 91; parameter();
					}
					}
					State = 96;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 14, RULE_argument);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99; expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentListContext : ParserRuleContext {
		public ArgumentContext[] argument() {
			return GetRuleContexts<ArgumentContext>();
		}
		public ArgumentContext argument(int i) {
			return GetRuleContext<ArgumentContext>(i);
		}
		public ITerminalNode[] FASLA() { return GetTokens(GeemParser.FASLA); }
		public ITerminalNode FASLA(int i) {
			return GetToken(GeemParser.FASLA, i);
		}
		public ArgumentListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argumentList; } }
	}

	[RuleVersion(0)]
	public ArgumentListContext argumentList() {
		ArgumentListContext _localctx = new ArgumentListContext(Context, State);
		EnterRule(_localctx, 16, RULE_argumentList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2) | (1L << T__3) | (1L << T__4) | (1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << RP) | (1L << MINUS) | (1L << LNOT))) != 0) || _la==ID) {
				{
				State = 101; argument();
				State = 106;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==FASLA) {
					{
					{
					State = 102; Match(FASLA);
					State = 103; argument();
					}
					}
					State = 108;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Lor_exprContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode LOR() { return GetToken(GeemParser.LOR, 0); }
		public Lor_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Add_exprContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode PLUS() { return GetToken(GeemParser.PLUS, 0); }
		public Add_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Land_exprContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode LAND() { return GetToken(GeemParser.LAND, 0); }
		public Land_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Comparison_exprContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Comparison_opContext comparison_op() {
			return GetRuleContext<Comparison_opContext>(0);
		}
		public Comparison_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Multiply_exprContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode MULTIPLY() { return GetToken(GeemParser.MULTIPLY, 0); }
		public Multiply_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Variable_exprContext : ExpressionContext {
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public Variable_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Parenthesis_exprContext : ExpressionContext {
		public ITerminalNode RP() { return GetToken(GeemParser.RP, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode LP() { return GetToken(GeemParser.LP, 0); }
		public Parenthesis_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Int_literal_exprContext : ExpressionContext {
		public Int_literalContext int_literal() {
			return GetRuleContext<Int_literalContext>(0);
		}
		public Int_literal_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Subtraction_exprContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode MINUS() { return GetToken(GeemParser.MINUS, 0); }
		public Subtraction_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Divide_exprContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode DIVIDE() { return GetToken(GeemParser.DIVIDE, 0); }
		public Divide_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Fun_call_exprContext : ExpressionContext {
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public ITerminalNode RP() { return GetToken(GeemParser.RP, 0); }
		public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		public ITerminalNode LP() { return GetToken(GeemParser.LP, 0); }
		public Fun_call_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Minus_exprContext : ExpressionContext {
		public ITerminalNode MINUS() { return GetToken(GeemParser.MINUS, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Minus_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Lnot_exprContext : ExpressionContext {
		public ITerminalNode LNOT() { return GetToken(GeemParser.LNOT, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Lnot_exprContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class Equality_exprContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Equality_opContext equality_op() {
			return GetRuleContext<Equality_opContext>(0);
		}
		public Equality_exprContext(ExpressionContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 18;
		EnterRecursionRule(_localctx, 18, RULE_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 127;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				_localctx = new Fun_call_exprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 112; Match(ID);
				State = 113; Match(RP);
				State = 114; argumentList();
				State = 115; Match(LP);
				}
				break;
			case 2:
				{
				_localctx = new Minus_exprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 117; Match(MINUS);
				State = 118; expression(13);
				}
				break;
			case 3:
				{
				_localctx = new Lnot_exprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 119; Match(LNOT);
				State = 120; expression(12);
				}
				break;
			case 4:
				{
				_localctx = new Parenthesis_exprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 121; Match(RP);
				State = 122; expression(0);
				State = 123; Match(LP);
				}
				break;
			case 5:
				{
				_localctx = new Int_literal_exprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 125; int_literal();
				}
				break;
			case 6:
				{
				_localctx = new Variable_exprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 126; Match(ID);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 157;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 155;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
					case 1:
						{
						_localctx = new Divide_exprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 129;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 130; Match(DIVIDE);
						State = 131; expression(12);
						}
						break;
					case 2:
						{
						_localctx = new Multiply_exprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 132;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 133; Match(MULTIPLY);
						State = 134; expression(11);
						}
						break;
					case 3:
						{
						_localctx = new Subtraction_exprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 135;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 136; Match(MINUS);
						State = 137; expression(10);
						}
						break;
					case 4:
						{
						_localctx = new Add_exprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 138;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 139; Match(PLUS);
						State = 140; expression(9);
						}
						break;
					case 5:
						{
						_localctx = new Comparison_exprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 141;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 142; comparison_op();
						State = 143; expression(8);
						}
						break;
					case 6:
						{
						_localctx = new Equality_exprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 145;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 146; equality_op();
						State = 147; expression(7);
						}
						break;
					case 7:
						{
						_localctx = new Land_exprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 149;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						{
						State = 150; Match(LAND);
						}
						State = 151; expression(6);
						}
						break;
					case 8:
						{
						_localctx = new Lor_exprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 152;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						{
						State = 153; Match(LOR);
						}
						State = 154; expression(5);
						}
						break;
					}
					} 
				}
				State = 159;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Int_literalContext : ParserRuleContext {
		public ITerminalNode COLON() { return GetToken(GeemParser.COLON, 0); }
		public ITerminalNode PLUS() { return GetToken(GeemParser.PLUS, 0); }
		public Int_literalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_int_literal; } }
	}

	[RuleVersion(0)]
	public Int_literalContext int_literal() {
		Int_literalContext _localctx = new Int_literalContext(Context, State);
		EnterRule(_localctx, 20, RULE_int_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 160;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2) | (1L << T__3) | (1L << T__4) | (1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 163;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2) | (1L << T__3) | (1L << T__4) | (1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9))) != 0) );
			State = 165; Match(COLON);
			State = 167;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PLUS) {
				{
				State = 166; Match(PLUS);
				}
			}

			State = 169;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__2) | (1L << T__4) | (1L << T__8))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Comparison_opContext : ParserRuleContext {
		public ITerminalNode GTE_SYM() { return GetToken(GeemParser.GTE_SYM, 0); }
		public ITerminalNode LTE_SYM() { return GetToken(GeemParser.LTE_SYM, 0); }
		public ITerminalNode GT_SYM() { return GetToken(GeemParser.GT_SYM, 0); }
		public ITerminalNode LT_SYM() { return GetToken(GeemParser.LT_SYM, 0); }
		public Comparison_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparison_op; } }
	}

	[RuleVersion(0)]
	public Comparison_opContext comparison_op() {
		Comparison_opContext _localctx = new Comparison_opContext(Context, State);
		EnterRule(_localctx, 22, RULE_comparison_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LTE_SYM) | (1L << GTE_SYM) | (1L << LT_SYM) | (1L << GT_SYM))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Equality_opContext : ParserRuleContext {
		public ITerminalNode EQUAL_SYM() { return GetToken(GeemParser.EQUAL_SYM, 0); }
		public ITerminalNode NOTEQ_SYM() { return GetToken(GeemParser.NOTEQ_SYM, 0); }
		public Equality_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_equality_op; } }
	}

	[RuleVersion(0)]
	public Equality_opContext equality_op() {
		Equality_opContext _localctx = new Equality_opContext(Context, State);
		EnterRule(_localctx, 24, RULE_equality_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			_la = TokenStream.LA(1);
			if ( !(_la==EQUAL_SYM || _la==NOTEQ_SYM) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	 
		public StatementContext() { }
		public virtual void CopyFrom(StatementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Command_StatContext : StatementContext {
		public CommandStatContext commandStat() {
			return GetRuleContext<CommandStatContext>(0);
		}
		public Command_StatContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class Var_Decl_StatContext : StatementContext {
		public VarDeclContext varDecl() {
			return GetRuleContext<VarDeclContext>(0);
		}
		public Var_Decl_StatContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class If_StatContext : StatementContext {
		public IfStatContext ifStat() {
			return GetRuleContext<IfStatContext>(0);
		}
		public If_StatContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class Return_StatContext : StatementContext {
		public ReturnStatContext returnStat() {
			return GetRuleContext<ReturnStatContext>(0);
		}
		public Return_StatContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class While_StatContext : StatementContext {
		public WhileStatContext whileStat() {
			return GetRuleContext<WhileStatContext>(0);
		}
		public While_StatContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class Result_StatContext : StatementContext {
		public ResultStatContext resultStat() {
			return GetRuleContext<ResultStatContext>(0);
		}
		public Result_StatContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class Operation_StatContext : StatementContext {
		public OperationStatContext operationStat() {
			return GetRuleContext<OperationStatContext>(0);
		}
		public Operation_StatContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class Assignment_StatContext : StatementContext {
		public AssignmentStatContext assignmentStat() {
			return GetRuleContext<AssignmentStatContext>(0);
		}
		public Assignment_StatContext(StatementContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 26, RULE_statement);
		try {
			State = 183;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				_localctx = new Assignment_StatContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 175; assignmentStat();
				}
				break;
			case 2:
				_localctx = new Return_StatContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 176; returnStat();
				}
				break;
			case 3:
				_localctx = new Result_StatContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 177; resultStat();
				}
				break;
			case 4:
				_localctx = new If_StatContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 178; ifStat();
				}
				break;
			case 5:
				_localctx = new While_StatContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 179; whileStat();
				}
				break;
			case 6:
				_localctx = new Var_Decl_StatContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 180; varDecl();
				}
				break;
			case 7:
				_localctx = new Operation_StatContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 181; operationStat();
				}
				break;
			case 8:
				_localctx = new Command_StatContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 182; commandStat();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementListContext : ParserRuleContext {
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public StatementListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statementList; } }
	}

	[RuleVersion(0)]
	public StatementListContext statementList() {
		StatementListContext _localctx = new StatementListContext(Context, State);
		EnterRule(_localctx, 28, RULE_statementList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((((_la - 24)) & ~0x3f) == 0 && ((1L << (_la - 24)) & ((1L << (COLON - 24)) | (1L << (RET_KEYWORD - 24)) | (1L << (RES_KEYWORD - 24)) | (1L << (IF_KEYWORD - 24)) | (1L << (WHILE_KEYWORD - 24)) | (1L << (INT_DATA_TYPE - 24)) | (1L << (UINT_DATA_TYPE - 24)) | (1L << (BYTE_DATA_TYPE - 24)) | (1L << (UBYTE_DATA_TYPE - 24)) | (1L << (SHORT_DATA_TYPE - 24)) | (1L << (USHORT_DATA_TYPE - 24)) | (1L << (LONG_DATA_TYPE - 24)) | (1L << (ULONG_DATA_TYPE - 24)) | (1L << (ID - 24)))) != 0)) {
				{
				{
				State = 185; statement();
				}
				}
				State = 190;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationStatContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public ITerminalNode RP() { return GetToken(GeemParser.RP, 0); }
		public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		public ITerminalNode LP() { return GetToken(GeemParser.LP, 0); }
		public ITerminalNode FASLA_MANQUOTA() { return GetToken(GeemParser.FASLA_MANQUOTA, 0); }
		public OperationStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operationStat; } }
	}

	[RuleVersion(0)]
	public OperationStatContext operationStat() {
		OperationStatContext _localctx = new OperationStatContext(Context, State);
		EnterRule(_localctx, 30, RULE_operationStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191; Match(ID);
			State = 192; Match(RP);
			State = 193; argumentList();
			State = 194; Match(LP);
			State = 195; Match(FASLA_MANQUOTA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentStatContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public ITerminalNode ASSIGN_SYM() { return GetToken(GeemParser.ASSIGN_SYM, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode FASLA_MANQUOTA() { return GetToken(GeemParser.FASLA_MANQUOTA, 0); }
		public AssignmentStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentStat; } }
	}

	[RuleVersion(0)]
	public AssignmentStatContext assignmentStat() {
		AssignmentStatContext _localctx = new AssignmentStatContext(Context, State);
		EnterRule(_localctx, 32, RULE_assignmentStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197; Match(ID);
			State = 198; Match(ASSIGN_SYM);
			State = 199; expression(0);
			State = 200; Match(FASLA_MANQUOTA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatContext : ParserRuleContext {
		public ITerminalNode IF_KEYWORD() { return GetToken(GeemParser.IF_KEYWORD, 0); }
		public ITerminalNode RP() { return GetToken(GeemParser.RP, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode LP() { return GetToken(GeemParser.LP, 0); }
		public ITerminalNode RCB() { return GetToken(GeemParser.RCB, 0); }
		public StatementListContext statementList() {
			return GetRuleContext<StatementListContext>(0);
		}
		public ITerminalNode LCB() { return GetToken(GeemParser.LCB, 0); }
		public IfStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStat; } }
	}

	[RuleVersion(0)]
	public IfStatContext ifStat() {
		IfStatContext _localctx = new IfStatContext(Context, State);
		EnterRule(_localctx, 34, RULE_ifStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 202; Match(IF_KEYWORD);
			State = 203; Match(RP);
			State = 204; expression(0);
			State = 205; Match(LP);
			State = 206; Match(RCB);
			State = 207; statementList();
			State = 208; Match(LCB);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatContext : ParserRuleContext {
		public ITerminalNode WHILE_KEYWORD() { return GetToken(GeemParser.WHILE_KEYWORD, 0); }
		public ITerminalNode RP() { return GetToken(GeemParser.RP, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode LP() { return GetToken(GeemParser.LP, 0); }
		public ITerminalNode RCB() { return GetToken(GeemParser.RCB, 0); }
		public StatementListContext statementList() {
			return GetRuleContext<StatementListContext>(0);
		}
		public ITerminalNode LCB() { return GetToken(GeemParser.LCB, 0); }
		public WhileStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStat; } }
	}

	[RuleVersion(0)]
	public WhileStatContext whileStat() {
		WhileStatContext _localctx = new WhileStatContext(Context, State);
		EnterRule(_localctx, 36, RULE_whileStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 210; Match(WHILE_KEYWORD);
			State = 211; Match(RP);
			State = 212; expression(0);
			State = 213; Match(LP);
			State = 214; Match(RCB);
			State = 215; statementList();
			State = 216; Match(LCB);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnStatContext : ParserRuleContext {
		public ITerminalNode RET_KEYWORD() { return GetToken(GeemParser.RET_KEYWORD, 0); }
		public ITerminalNode FASLA_MANQUOTA() { return GetToken(GeemParser.FASLA_MANQUOTA, 0); }
		public ReturnStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnStat; } }
	}

	[RuleVersion(0)]
	public ReturnStatContext returnStat() {
		ReturnStatContext _localctx = new ReturnStatContext(Context, State);
		EnterRule(_localctx, 38, RULE_returnStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 218; Match(RET_KEYWORD);
			State = 219; Match(FASLA_MANQUOTA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ResultStatContext : ParserRuleContext {
		public ITerminalNode RES_KEYWORD() { return GetToken(GeemParser.RES_KEYWORD, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode FASLA_MANQUOTA() { return GetToken(GeemParser.FASLA_MANQUOTA, 0); }
		public ResultStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_resultStat; } }
	}

	[RuleVersion(0)]
	public ResultStatContext resultStat() {
		ResultStatContext _localctx = new ResultStatContext(Context, State);
		EnterRule(_localctx, 40, RULE_resultStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 221; Match(RES_KEYWORD);
			State = 222; expression(0);
			State = 223; Match(FASLA_MANQUOTA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarDeclContext : ParserRuleContext {
		public DataTypeContext dataType() {
			return GetRuleContext<DataTypeContext>(0);
		}
		public ITerminalNode ID() { return GetToken(GeemParser.ID, 0); }
		public InititalizationContext inititalization() {
			return GetRuleContext<InititalizationContext>(0);
		}
		public ITerminalNode FASLA_MANQUOTA() { return GetToken(GeemParser.FASLA_MANQUOTA, 0); }
		public VarDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varDecl; } }
	}

	[RuleVersion(0)]
	public VarDeclContext varDecl() {
		VarDeclContext _localctx = new VarDeclContext(Context, State);
		EnterRule(_localctx, 42, RULE_varDecl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 225; dataType();
			State = 226; Match(ID);
			State = 227; inititalization();
			State = 228; Match(FASLA_MANQUOTA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandStatContext : ParserRuleContext {
		public CommandContext command() {
			return GetRuleContext<CommandContext>(0);
		}
		public ITerminalNode FASLA_MANQUOTA() { return GetToken(GeemParser.FASLA_MANQUOTA, 0); }
		public CommandStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commandStat; } }
	}

	[RuleVersion(0)]
	public CommandStatContext commandStat() {
		CommandStatContext _localctx = new CommandStatContext(Context, State);
		EnterRule(_localctx, 44, RULE_commandStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 230; command();
			State = 231; Match(FASLA_MANQUOTA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DataTypeContext : ParserRuleContext {
		public ITerminalNode INT_DATA_TYPE() { return GetToken(GeemParser.INT_DATA_TYPE, 0); }
		public ITerminalNode UINT_DATA_TYPE() { return GetToken(GeemParser.UINT_DATA_TYPE, 0); }
		public ITerminalNode BYTE_DATA_TYPE() { return GetToken(GeemParser.BYTE_DATA_TYPE, 0); }
		public ITerminalNode UBYTE_DATA_TYPE() { return GetToken(GeemParser.UBYTE_DATA_TYPE, 0); }
		public ITerminalNode SHORT_DATA_TYPE() { return GetToken(GeemParser.SHORT_DATA_TYPE, 0); }
		public ITerminalNode USHORT_DATA_TYPE() { return GetToken(GeemParser.USHORT_DATA_TYPE, 0); }
		public ITerminalNode LONG_DATA_TYPE() { return GetToken(GeemParser.LONG_DATA_TYPE, 0); }
		public ITerminalNode ULONG_DATA_TYPE() { return GetToken(GeemParser.ULONG_DATA_TYPE, 0); }
		public DataTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dataType; } }
	}

	[RuleVersion(0)]
	public DataTypeContext dataType() {
		DataTypeContext _localctx = new DataTypeContext(Context, State);
		EnterRule(_localctx, 46, RULE_dataType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 233;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INT_DATA_TYPE) | (1L << UINT_DATA_TYPE) | (1L << BYTE_DATA_TYPE) | (1L << UBYTE_DATA_TYPE) | (1L << SHORT_DATA_TYPE) | (1L << USHORT_DATA_TYPE) | (1L << LONG_DATA_TYPE) | (1L << ULONG_DATA_TYPE))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode COLON() { return GetToken(GeemParser.COLON, 0); }
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 48, RULE_command);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 235; Match(COLON);
			State = 236;
			_la = TokenStream.LA(1);
			if ( !(_la==T__10 || _la==T__11) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
			State = 238; expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 9: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 11);
		case 1: return Precpred(Context, 10);
		case 2: return Precpred(Context, 9);
		case 3: return Precpred(Context, 8);
		case 4: return Precpred(Context, 7);
		case 5: return Precpred(Context, 6);
		case 6: return Precpred(Context, 5);
		case 7: return Precpred(Context, 4);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x44', '\xF3', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x6', '\x2', '\x39', 
		'\n', '\x2', '\r', '\x2', '\xE', '\x2', ':', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\a', '\b', '_', '\n', '\b', '\f', '\b', '\xE', '\b', 
		'\x62', '\v', '\b', '\x5', '\b', '\x64', '\n', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\a', '\n', 'k', '\n', '\n', 
		'\f', '\n', '\xE', '\n', 'n', '\v', '\n', '\x5', '\n', 'p', '\n', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', 
		'\v', '\x82', '\n', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\a', '\v', '\x9E', '\n', '\v', '\f', '\v', '\xE', '\v', '\xA1', 
		'\v', '\v', '\x3', '\f', '\x6', '\f', '\xA4', '\n', '\f', '\r', '\f', 
		'\xE', '\f', '\xA5', '\x3', '\f', '\x3', '\f', '\x5', '\f', '\xAA', '\n', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 
		'\xBA', '\n', '\xF', '\x3', '\x10', '\a', '\x10', '\xBD', '\n', '\x10', 
		'\f', '\x10', '\xE', '\x10', '\xC0', '\v', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x2', '\x3', '\x14', 
		'\x1B', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', 
		'*', ',', '.', '\x30', '\x32', '\x2', '\b', '\x3', '\x2', '\x3', '\f', 
		'\x5', '\x2', '\x4', '\x5', '\a', '\a', '\v', '\v', '\x3', '\x2', '+', 
		'.', '\x3', '\x2', '/', '\x30', '\x3', '\x2', ':', '\x41', '\x3', '\x2', 
		'\r', '\xE', '\x2', '\xF8', '\x2', '\x38', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '<', '\x3', '\x2', '\x2', '\x2', '\x6', '\x41', '\x3', '\x2', '\x2', 
		'\x2', '\b', '\x44', '\x3', '\x2', '\x2', '\x2', '\n', 'O', '\x3', '\x2', 
		'\x2', '\x2', '\f', 'X', '\x3', '\x2', '\x2', '\x2', '\xE', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x10', '\x65', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'o', '\x3', '\x2', '\x2', '\x2', '\x14', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x16', '\xA3', '\x3', '\x2', '\x2', '\x2', '\x18', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', '\xAF', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'\xB9', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', ' ', '\xC1', '\x3', '\x2', '\x2', '\x2', '\"', '\xC7', '\x3', '\x2', 
		'\x2', '\x2', '$', '\xCC', '\x3', '\x2', '\x2', '\x2', '&', '\xD4', '\x3', 
		'\x2', '\x2', '\x2', '(', '\xDC', '\x3', '\x2', '\x2', '\x2', '*', '\xDF', 
		'\x3', '\x2', '\x2', '\x2', ',', '\xE3', '\x3', '\x2', '\x2', '\x2', '.', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', '\x30', '\xEB', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\xED', '\x3', '\x2', '\x2', '\x2', '\x34', '\x39', '\x5', 
		'\x4', '\x3', '\x2', '\x35', '\x39', '\x5', '\b', '\x5', '\x2', '\x36', 
		'\x39', '\x5', '\n', '\x6', '\x2', '\x37', '\x39', '\x5', '.', '\x18', 
		'\x2', '\x38', '\x34', '\x3', '\x2', '\x2', '\x2', '\x38', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x38', '\x36', '\x3', '\x2', '\x2', '\x2', '\x38', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\x3', '\x2', '\x2', 
		'\x2', ':', '\x38', '\x3', '\x2', '\x2', '\x2', ':', ';', '\x3', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x3', '\x2', '\x2', '\x2', '<', '=', '\x5', 
		'\x30', '\x19', '\x2', '=', '>', '\a', '\x44', '\x2', '\x2', '>', '?', 
		'\x5', '\x6', '\x4', '\x2', '?', '@', '\a', '\x19', '\x2', '\x2', '@', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\x31', '\x2', 
		'\x2', '\x42', '\x43', '\x5', '\x14', '\v', '\x2', '\x43', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x45', '\a', '\x32', '\x2', '\x2', '\x45', 
		'\x46', '\a', '\x44', '\x2', '\x2', '\x46', 'G', '\a', '\x10', '\x2', 
		'\x2', 'G', 'H', '\x5', '\xE', '\b', '\x2', 'H', 'I', '\a', '\xF', '\x2', 
		'\x2', 'I', 'J', '\a', '\x1A', '\x2', '\x2', 'J', 'K', '\x5', '\x30', 
		'\x19', '\x2', 'K', 'L', '\a', '\x14', '\x2', '\x2', 'L', 'M', '\x5', 
		'\x1E', '\x10', '\x2', 'M', 'N', '\a', '\x13', '\x2', '\x2', 'N', '\t', 
		'\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', '\x33', '\x2', '\x2', 'P', 
		'Q', '\a', '\x44', '\x2', '\x2', 'Q', 'R', '\a', '\x10', '\x2', '\x2', 
		'R', 'S', '\x5', '\xE', '\b', '\x2', 'S', 'T', '\a', '\xF', '\x2', '\x2', 
		'T', 'U', '\a', '\x14', '\x2', '\x2', 'U', 'V', '\x5', '\x1E', '\x10', 
		'\x2', 'V', 'W', '\a', '\x13', '\x2', '\x2', 'W', '\v', '\x3', '\x2', 
		'\x2', '\x2', 'X', 'Y', '\x5', '\x30', '\x19', '\x2', 'Y', 'Z', '\a', 
		'\x44', '\x2', '\x2', 'Z', '\r', '\x3', '\x2', '\x2', '\x2', '[', '`', 
		'\x5', '\f', '\a', '\x2', '\\', ']', '\a', '\x18', '\x2', '\x2', ']', 
		'_', '\x5', '\f', '\a', '\x2', '^', '\\', '\x3', '\x2', '\x2', '\x2', 
		'_', '\x62', '\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '\x64', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'[', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\xF', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\x5', 
		'\x14', '\v', '\x2', '\x66', '\x11', '\x3', '\x2', '\x2', '\x2', 'g', 
		'l', '\x5', '\x10', '\t', '\x2', 'h', 'i', '\a', '\x18', '\x2', '\x2', 
		'i', 'k', '\x5', '\x10', '\t', '\x2', 'j', 'h', '\x3', '\x2', '\x2', '\x2', 
		'k', 'n', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', 'p', '\x3', '\x2', '\x2', '\x2', 
		'n', 'l', '\x3', '\x2', '\x2', '\x2', 'o', 'g', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', '\x13', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\b', '\v', '\x1', '\x2', 'r', 's', '\a', '\x44', '\x2', 
		'\x2', 's', 't', '\a', '\x10', '\x2', '\x2', 't', 'u', '\x5', '\x12', 
		'\n', '\x2', 'u', 'v', '\a', '\xF', '\x2', '\x2', 'v', '\x82', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'x', '\a', '\x1C', '\x2', '\x2', 'x', '\x82', 
		'\x5', '\x14', '\v', '\xF', 'y', 'z', '\a', '#', '\x2', '\x2', 'z', '\x82', 
		'\x5', '\x14', '\v', '\xE', '{', '|', '\a', '\x10', '\x2', '\x2', '|', 
		'}', '\x5', '\x14', '\v', '\x2', '}', '~', '\a', '\xF', '\x2', '\x2', 
		'~', '\x82', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x82', '\x5', '\x16', 
		'\f', '\x2', '\x80', '\x82', '\a', '\x44', '\x2', '\x2', '\x81', 'q', 
		'\x3', '\x2', '\x2', '\x2', '\x81', 'w', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'y', '\x3', '\x2', '\x2', '\x2', '\x81', '{', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x82', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', 
		'\f', '\r', '\x2', '\x2', '\x84', '\x85', '\a', '\x1E', '\x2', '\x2', 
		'\x85', '\x9E', '\x5', '\x14', '\v', '\xE', '\x86', '\x87', '\f', '\f', 
		'\x2', '\x2', '\x87', '\x88', '\a', '\x1D', '\x2', '\x2', '\x88', '\x9E', 
		'\x5', '\x14', '\v', '\r', '\x89', '\x8A', '\f', '\v', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', '\x1C', '\x2', '\x2', '\x8B', '\x9E', '\x5', '\x14', '\v', 
		'\f', '\x8C', '\x8D', '\f', '\n', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'\x1B', '\x2', '\x2', '\x8E', '\x9E', '\x5', '\x14', '\v', '\v', '\x8F', 
		'\x90', '\f', '\t', '\x2', '\x2', '\x90', '\x91', '\x5', '\x18', '\r', 
		'\x2', '\x91', '\x92', '\x5', '\x14', '\v', '\n', '\x92', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x94', '\f', '\b', '\x2', '\x2', '\x94', 
		'\x95', '\x5', '\x1A', '\xE', '\x2', '\x95', '\x96', '\x5', '\x14', '\v', 
		'\t', '\x96', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\f', 
		'\a', '\x2', '\x2', '\x98', '\x99', '\a', '!', '\x2', '\x2', '\x99', '\x9E', 
		'\x5', '\x14', '\v', '\b', '\x9A', '\x9B', '\f', '\x6', '\x2', '\x2', 
		'\x9B', '\x9C', '\a', '\"', '\x2', '\x2', '\x9C', '\x9E', '\x5', '\x14', 
		'\v', '\a', '\x9D', '\x83', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x86', 
		'\x3', '\x2', '\x2', '\x2', '\x9D', '\x89', '\x3', '\x2', '\x2', '\x2', 
		'\x9D', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x8F', '\x3', '\x2', 
		'\x2', '\x2', '\x9D', '\x93', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x9D', '\x9A', '\x3', '\x2', '\x2', '\x2', 
		'\x9E', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\x9F', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x15', 
		'\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\xA2', '\xA4', '\t', '\x2', '\x2', '\x2', '\xA3', '\xA2', '\x3', '\x2', 
		'\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\xA6', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA9', '\a', '\x1A', 
		'\x2', '\x2', '\xA8', '\xAA', '\a', '\x1B', '\x2', '\x2', '\xA9', '\xA8', 
		'\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', 
		'\xAA', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\t', '\x3', 
		'\x2', '\x2', '\xAC', '\x17', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', 
		'\t', '\x4', '\x2', '\x2', '\xAE', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\xB0', '\t', '\x5', '\x2', '\x2', '\xB0', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\xB1', '\xBA', '\x5', '\"', '\x12', '\x2', '\xB2', '\xBA', 
		'\x5', '(', '\x15', '\x2', '\xB3', '\xBA', '\x5', '*', '\x16', '\x2', 
		'\xB4', '\xBA', '\x5', '$', '\x13', '\x2', '\xB5', '\xBA', '\x5', '&', 
		'\x14', '\x2', '\xB6', '\xBA', '\x5', ',', '\x17', '\x2', '\xB7', '\xBA', 
		'\x5', ' ', '\x11', '\x2', '\xB8', '\xBA', '\x5', '.', '\x18', '\x2', 
		'\xB9', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', '\xB9', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB4', 
		'\x3', '\x2', '\x2', '\x2', '\xB9', '\xB5', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB7', '\x3', '\x2', 
		'\x2', '\x2', '\xB9', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBA', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\xBB', '\xBD', '\x5', '\x1C', '\xF', '\x2', 
		'\xBC', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', 
		'\x3', '\x2', '\x2', '\x2', '\xBF', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\xC0', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\a', '\x44', 
		'\x2', '\x2', '\xC2', '\xC3', '\a', '\x10', '\x2', '\x2', '\xC3', '\xC4', 
		'\x5', '\x12', '\n', '\x2', '\xC4', '\xC5', '\a', '\xF', '\x2', '\x2', 
		'\xC5', '\xC6', '\a', '\x19', '\x2', '\x2', '\xC6', '!', '\x3', '\x2', 
		'\x2', '\x2', '\xC7', '\xC8', '\a', '\x44', '\x2', '\x2', '\xC8', '\xC9', 
		'\a', '\x31', '\x2', '\x2', '\xC9', '\xCA', '\x5', '\x14', '\v', '\x2', 
		'\xCA', '\xCB', '\a', '\x19', '\x2', '\x2', '\xCB', '#', '\x3', '\x2', 
		'\x2', '\x2', '\xCC', '\xCD', '\a', '\x36', '\x2', '\x2', '\xCD', '\xCE', 
		'\a', '\x10', '\x2', '\x2', '\xCE', '\xCF', '\x5', '\x14', '\v', '\x2', 
		'\xCF', '\xD0', '\a', '\xF', '\x2', '\x2', '\xD0', '\xD1', '\a', '\x14', 
		'\x2', '\x2', '\xD1', '\xD2', '\x5', '\x1E', '\x10', '\x2', '\xD2', '\xD3', 
		'\a', '\x13', '\x2', '\x2', '\xD3', '%', '\x3', '\x2', '\x2', '\x2', '\xD4', 
		'\xD5', '\a', '\x37', '\x2', '\x2', '\xD5', '\xD6', '\a', '\x10', '\x2', 
		'\x2', '\xD6', '\xD7', '\x5', '\x14', '\v', '\x2', '\xD7', '\xD8', '\a', 
		'\xF', '\x2', '\x2', '\xD8', '\xD9', '\a', '\x14', '\x2', '\x2', '\xD9', 
		'\xDA', '\x5', '\x1E', '\x10', '\x2', '\xDA', '\xDB', '\a', '\x13', '\x2', 
		'\x2', '\xDB', '\'', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', '\a', 
		'\x34', '\x2', '\x2', '\xDD', '\xDE', '\a', '\x19', '\x2', '\x2', '\xDE', 
		')', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE0', '\a', '\x35', '\x2', 
		'\x2', '\xE0', '\xE1', '\x5', '\x14', '\v', '\x2', '\xE1', '\xE2', '\a', 
		'\x19', '\x2', '\x2', '\xE2', '+', '\x3', '\x2', '\x2', '\x2', '\xE3', 
		'\xE4', '\x5', '\x30', '\x19', '\x2', '\xE4', '\xE5', '\a', '\x44', '\x2', 
		'\x2', '\xE5', '\xE6', '\x5', '\x6', '\x4', '\x2', '\xE6', '\xE7', '\a', 
		'\x19', '\x2', '\x2', '\xE7', '-', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xE9', '\x5', '\x32', '\x1A', '\x2', '\xE9', '\xEA', '\a', '\x19', '\x2', 
		'\x2', '\xEA', '/', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xEC', '\t', 
		'\x6', '\x2', '\x2', '\xEC', '\x31', '\x3', '\x2', '\x2', '\x2', '\xED', 
		'\xEE', '\a', '\x1A', '\x2', '\x2', '\xEE', '\xEF', '\t', '\a', '\x2', 
		'\x2', '\xEF', '\xF0', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF1', '\x5', 
		'\x14', '\v', '\x2', '\xF1', '\x33', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x38', ':', '`', '\x63', 'l', 'o', '\x81', '\x9D', '\x9F', '\xA5', '\xA9', 
		'\xB9', '\xBE',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Geem.Parser
